#!/bin/bash

############################################################
#
#
#
#    BOX
#    --------------------------------------------------
#
#    Copyright 2015 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################


# Print a message.
echo "Installing..."
echo "-- install box /usr/local/bin"
sudo install box /usr/local/bin

# Delete the config folder in the home directory if it exists.
if [ -d $HOME/.box.d ]; then
    echo "-- deleting config from $HOME/.box.d...";
    rm -rf $HOME/.box.d
fi

# Now create a new config folder and copy the config to it.
echo "-- copying config to $HOME/.box.d...";
mkdir $HOME/.box.d
cp -r config $HOME/.box.d/

# We're done.
echo "-- done"
exit 0
