#!/usr/bin/env bash

############################################################
#
#
#
#    BOX
#    --------------------------------------------------
#
#    Copyright 2015 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################

# Update apt-get.
sudo apt-get update

# Install vim, emacs, and git.
sudo apt-get install -y vim
sudo apt-get install -y emacs24-nox
sudo apt-get install -y git
sudo apt-get install -y wget
sudo apt-get install -y curl

# Execute any other scripts in this directory.
PROVISION_SCRIPTS=/vagrant/config/bash/*
THIS_SCRIPT=/vagrant/config/bash/provision
for SCRIPT in $PROVISION_SCRIPTS ; do
    if [ $SCRIPT != $THIS_SCRIPT ]; then
        source $SCRIPT
    fi
done

# Leave a message.
echo "Finished provisioning."

# Exit cleanly.
exit 0
