#!/bin/bash

############################################################
#
#
#
#    BOX
#    --------------------------------------------------
#
#    Copyright 2015 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################

# Update apt-get.
sudo apt-get update

# Install vim, emacs, and git.
sudo apt-get install -y vim
sudo apt-get install -y emacs24-nox
sudo apt-get install -y git


# Leave a message.
echo "Finished provisioning."

# Exit cleanly.
exit 0
