# -*- mode: ruby -*-
# vi: set ft=ruby :

############################################################
#
#
#
#    BOX
#    --------------------------------------------------
#
#    Copyright 2015 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################


# What vagrant version is required?
Vagrant.require_version '>= 1.7.2'

# Now configure the VM.
Vagrant.configure(2) do |configure|

  # The name of the base box.
  configure.vm.box = 'ubuntu/vivid64'

  # Use a private network.
  configure.vm.network :private_network, ip: '11.22.33.44'

  # Share a folder with the VM.
  configure.vm.synced_folder '..', '/home/vagrant/code'

  # Provision with a shell script.
  configure.vm.provision "shell",
    path: "config/bash/provision" 

end
