#!/usr/bin/env bash

############################################################
#
#
#
#    BOX
#    --------------------------------------------------
#
#    Copyright 2015 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################


# Install some python requirements.
sudo apt-get install -y make 
sudo apt-get install -y build-essential 
sudo apt-get install -y libssl-dev 
sudo apt-get install -y zlib1g-dev
sudo apt-get install -y libbz2-dev
sudo apt-get install -y libreadline-dev 
sudo apt-get install -y libsqlite3-dev 
sudo apt-get install -y llvm

# Install pyenv and python 3.4.3, as the vagrant user.
sudo su vagrant <<'EOF' 

# If no pyenv, install it.
if [ hash pyenv 2>/dev/null; then
    curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
    echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bash_profile
    echo 'export PATH="$HOME/.pyenv/bin:$PATH"' >> ~/.bash_profile
    echo 'eval "$(pyenv init -)"' >> ~/.bash_profile
    echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.bash_profile
fi

# Load the vagrant's bash profile so 
# we have the `pyenv` command available to us.
. ~/.bash_profile

# If Python 3.4.3 is not installed, install it.
PYTHON_343=`pyenv versions | grep -o '3\.4\.3'`
if [ "$PYTHON_343" != "3.4.3" ]; then
    pyenv install 3.4.3
    pyenv rehash
fi 

EOF
